Repository wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-2-7, pull requests merged in 2023-08, with the labels that each got.

#4 feat: #3 초기 페이지 파일 생성 및 라우터 설정
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/Layout/Layout.tsx
  src/pages/ErrorPage.tsx
  src/pages/IssueDetailPage.tsx
  src/pages/IssuesPage.tsx
  src/pages/PageRouter.tsx
Labels: feat

#7 feat: #6 IssuesPage 기본 기능, Loading/Error 처리, owner/repo input data로 조회 추가 기능 작업
  src/App.tsx
  src/apis/issue.ts
  src/components/Issues/IssueList.tsx
  src/components/Issues/IssueListError.tsx
  src/components/Issues/Loading.tsx
  src/components/Issues/Select.tsx
  src/hooks/useIssue.tsx
  src/pages/IssuesPage.tsx
Labels: feat

#14 feat: #10 favicon, meta data 변경, og 태그 변경
  public/favicon.ico
  public/index.html
Labels: feat

#15 style: #11 global style 정의 및 기본 레이아웃 스타일 설정
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/Header/Header.styled.ts
  src/components/Header/Header.tsx
  src/components/Layout/Layout.styled.ts
  src/components/Layout/Layout.tsx
  src/styles/base/DefaultTheme.ts
  src/styles/base/GlobalStyles.ts
  src/styles/constants/colors.ts
  src/styles/constants/flex.ts
  src/styles/constants/fontSize.ts
Labels: style

#16 refactor: #8 이슈 페이지 개선
  src/App.tsx
  src/apis/issue.ts
  src/components/Issues/ImageBanner.tsx
  src/components/Issues/IssueList.tsx
  src/components/Issues/Select.tsx
  src/components/Issues/constant.ts
  src/hooks/useIssue.tsx
  src/hooks/useIssueListContext.ts
  src/pages/IssuesPage.tsx
  src/store/IssuesContext.tsx
Labels: refactor

#18 style: #17 404 에러 페이지 스타일 추가
  src/components/Error/Error.styled.ts
  src/pages/ErrorPage.tsx
  src/styles/constants/flex.ts
Labels: style

#24 style: #20 이슈 리스트 페이지 스타일 적용
  src/components/Header/Header.styled.ts
  src/components/Issues/IssueList.tsx
  src/components/Issues/Issues.styled.ts
  src/components/Issues/Loading.tsx
  src/components/Issues/Select.tsx
  src/pages/IssuesPage.tsx
  src/styles/base/DefaultTheme.ts
  src/styles/base/GlobalStyles.ts
  src/styles/constants/colors.ts
Labels: style

#28 config: #19 Github Actions 추가
  .github/workflows/main.yml
Labels: config

#27 feat: #5 이슈 상세 페이지 제작하기
  package-lock.json
  package.json
  src/apis/issue.ts
  src/components/IssueDetail/IssueBody.tsx
  src/components/IssueDetail/IssueDetail.styled.ts
  src/components/IssueDetail/IssueTitle.tsx
  src/components/IssueDetail/type.ts
  src/components/Issues/IssueList.tsx
  src/pages/IssueDetailPage.tsx
  src/styles/constants/flex.ts
Labels: feat
