Repository wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-2-7, pull requests merged in 2023-09, with the labels that each got.

#30 Fix #22 scroll bug
  src/components/Issues/Issues.styled.ts
  src/hooks/useIssue.tsx
  src/pages/IssuesPage.tsx
Labels: bug

#31 config: #29 sort-import ESLint 룰 추가
  .eslintrc.js
  package-lock.json
  package.json
  src/App.tsx
  src/components/Error/Error.styled.ts
  src/components/Header/Header.styled.ts
  src/components/IssueDetail/IssueBody.tsx
  src/components/Issues/IssueList.tsx
  src/components/Issues/Issues.styled.ts
  src/hooks/useIssue.tsx
  src/hooks/useIssueListContext.ts
  src/index.tsx
  src/pages/IssueDetailPage.tsx
  src/pages/IssuesPage.tsx
  src/pages/PageRouter.tsx
  src/store/IssuesContext.tsx
  src/styles/base/GlobalStyles.ts
Labels: config

#34 refactor: #23, #25 ThemeProvider 타입추론 적용, 상수 추가 후 적용
  src/components/Error/Error.styled.ts
  src/components/Header/Header.styled.ts
  src/components/Issues/Issues.styled.ts
  src/styles/base/DefaultTheme.ts
  src/styles/base/GlobalStyles.ts
  src/styles/base/styled.d.ts
  src/styles/constants/colors.ts
  src/styles/constants/flex.ts
  src/styles/constants/fontSize.ts
Labels: refactor

#37 fix: #32 다른 owner/repo 조회 시 issuesList 초기화 되지 않는 버그
  src/components/Header/Header.tsx
  src/components/Issues/IssueListError.tsx
  src/components/Issues/Select.tsx
  src/hooks/useIssue.tsx
  src/pages/IssuesPage.tsx
  src/store/IssuesContext.tsx
Labels: bug

#38 feat: #33 서버 에러(500대) 페이지 생성
  src/apis/instance.ts
  src/pages/PageRouter.tsx
  src/pages/ServerErrorPage.tsx
Labels: feat

#42 fix: loadMoreBox 노출 조건 수정
  src/pages/IssuesPage.tsx
Labels: bug

#43 style: #40 이슈리스트 에러 스타일 적용
  package-lock.json
  package.json
  src/components/Issues/IssueListError.tsx
  src/components/Issues/Issues.styled.ts
Labels: style
